import 'package:hive_ce_flutter/adapters.dart';

part 'credentials.g.dart'; // This will be generated by build_runner

@HiveType(typeId: 1)
class SonarrCredentials extends HiveObject {
  @HiveField(0)
  final String sonarrUrl;

  @HiveField(1)
  final String sonarrApi;

  SonarrCredentials({required this.sonarrUrl, required this.sonarrApi});

  @override
  String toString() =>
      'SonarrCredentials(url: $sonarrUrl, api: ${sonarrApi.substring(0, 8)}...)';
}

@HiveType(typeId: 2)
class RadarrCredentials extends HiveObject {
  @HiveField(0)
  final String radarrUrl;

  @HiveField(1)
  final String radarrApi;

  RadarrCredentials({required this.radarrUrl, required this.radarrApi});

  @override
  String toString() =>
      'RadarrCredentials(url: $radarrUrl, api: ${radarrApi.substring(0, 8)}...)';
}
