// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:client/src/core/domain/credentials.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CredentialsAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CredentialsAdapter());
  }
}
